// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_new_beginnings = "CgkIq77noacSEAIQBA"; // <GPGSID>
        public const string achievement_lose_a_game_without_getting_a_point = "CgkIq77noacSEAIQCg"; // <GPGSID>
        public const string achievement_start_game = "CgkIq77noacSEAIQAA"; // <GPGSID>
        public const string achievement_achieve_high_score_of_5_in_match = "CgkIq77noacSEAIQBw"; // <GPGSID>
        public const string leaderboard_classic_high_score = "CgkIq77noacSEAIQAQ"; // <GPGSID>
        public const string achievement_achieve_high_score_of_101_in_timed_round_mode = "CgkIq77noacSEAIQBg"; // <GPGSID>
        public const string achievement_achieve_high_score_of_12_in_classic_mode = "CgkIq77noacSEAIQAw"; // <GPGSID>
        public const string achievement_play_all_the_game_modes = "CgkIq77noacSEAIQCA"; // <GPGSID>
        public const string achievement_achieve_a_score_of_13_in_classic_mode_in_under_120_seconds = "CgkIq77noacSEAIQCQ"; // <GPGSID>
        public const string achievement_achieve_high_score_of_8_in_random_mode = "CgkIq77noacSEAIQBQ"; // <GPGSID>

}

