// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_i_have_no_matches = "CgkIq77noacSEAIQBw"; // <GPGSID>
        public const string achievement_9000_great_taps = "CgkIq77noacSEAIQDA"; // <GPGSID>
        public const string achievement_a_week_of_patterns = "CgkIq77noacSEAIQDg"; // <GPGSID>
        public const string achievement_you_are_speed = "CgkIq77noacSEAIQCQ"; // <GPGSID>
        public const string achievement_its_coming_home = "CgkIq77noacSEAIQDQ"; // <GPGSID>
        public const string achievement_so_many_dogs = "CgkIq77noacSEAIQBg"; // <GPGSID>
        public const string achievement_on_the_12th_day = "CgkIq77noacSEAIQAw"; // <GPGSID>
        public const string leaderboard_classic_high_score = "CgkIq77noacSEAIQAQ"; // <GPGSID>
        public const string achievement_not_a_single_error = "CgkIq77noacSEAIQDw"; // <GPGSID>
        public const string achievement_new_beginnings = "CgkIq77noacSEAIQBA"; // <GPGSID>
        public const string achievement_finest_hour = "CgkIq77noacSEAIQEQ"; // <GPGSID>
        public const string achievement_a_humble_defeat = "CgkIq77noacSEAIQCg"; // <GPGSID>
        public const string achievement_luck_of_the_irish = "CgkIq77noacSEAIQEA"; // <GPGSID>
        public const string achievement_play_all_the_game_modes = "CgkIq77noacSEAIQCA"; // <GPGSID>
        public const string achievement_start_game = "CgkIq77noacSEAIQAA"; // <GPGSID>
        public const string achievement_a_slanted_grate = "CgkIq77noacSEAIQBQ"; // <GPGSID>
        public const string achievement_1000_good_taps = "CgkIq77noacSEAIQCw"; // <GPGSID>

}

